<%

require 'run_loop'

date = Time.now.strftime('%Y-%m-%d-%H%M-%S')

FileUtils.mkdir("./screenshots") unless File.exists?("./screenshots")
FileUtils.mkdir("./reports") unless File.exists?("./reports")

xamarin_dir = "#{ENV['HOME']}/.xamarin"

devices = {}

device_list = ['pluto', 'neptune', 'venus', 'earp', 'mars', 'pegasi', 'uranus', 'hatp']

device_list.each do |device|
  dir = "#{xamarin_dir}/devices/#{device}"
  ip = IO.read("#{dir}/ip") if File.exists?("#{dir}/ip")
  udid = IO.read("#{dir}/udid") if File.exists?("#{dir}/udid")
  report = "./reports/#{device}/#{date}-#{device}.html"
  ss_path = "./reports/#{device}/screenshots/"
  ht = {:dir => dir,
        :ip => ip,
        :udid => udid,
        :report => report,
        :ss_path => ss_path}
  devices[device.to_sym] = ht

  FileUtils.mkdir("./reports/#{device}") unless File.exists?("./reports/#{device}")
  FileUtils.mkdir("./reports/#{device}/screenshots") unless File.exists?("./reports/#{device}/screenshots")
end

xcode_tools = RunLoop::XCTools.new
sims = {}
if xcode_tools.xcode_version_gte_6?
  sims[:ipad2]     = 'iPad 2 (8.0 Simulator)'
  sims[:ipad2_mid] = 'iPad 2 (7.1 Simulator)'
  sims[:ipad2_min] = 'iPad 2 (7.0.3 Simulator)'

  sims[:air] =     'iPad Air (8.0 Simulator)'
  sims[:air_mid] = 'iPad Air (7.1 Simulator)'
  sims[:air_min] = 'iPad Air (7.0.3 Simulator)'

  sims[:ipad]     = 'iPad Retina (8.0 Simulator)'
  sims[:ipad_mid] = 'iPad Retina (7.1 Simulator)'
  sims[:ipad_min] = 'iPad Retina (7.0.3 Simulator)'

  sims[:iphone4s]     = 'iPhone 4s (8.0 Simulator)'
  sims[:iphone4s_mid] = 'iPhone 4s (7.1 Simulator)'
  sims[:iphone4s_min] = 'iPhone 4s (7.0.3 Simulator)'

  sims[:iphone5s]     = 'iPhone 5s (8.0 Simulator)'
  sims[:iphone5s_mid] = 'iPhone 5s (7.1 Simulator)'
  sims[:iphone5s_min] = 'iPhone 5s (7.0.3 Simulator)'

  sims[:iphone5]     = 'iPhone 5 (8.0 Simulator)'
  sims[:iphone5_mid] = 'iPhone 5 (7.1 Simulator)'
  sims[:iphone5_min] = 'iPhone 5 (7.0.3 Simulator)'

  sims[:iphone_latest] = 'iPhone 6 (8.0 Simulator)'
  sims[:iphone_largest] = 'iPhone 6 Plus (8.0 Simulator)'

  sims[:default]     = 'iPhone 5 (8.0 Simulator)'
else
  sims[:ipad2]     = 'iPad - Simulator - iOS 7.1'
  sims[:ipad2_mid] = 'iPad - Simulator - iOS 7.0'
  sims[:ipad2_min] = 'iPad - Simulator - iOS 6.1'

  sims[:air] =     'iPad Retina (64-bit) - Simulator - iOS 7.1'
  sims[:air_mid] = 'iPad Retina (64-bit) - Simulator - iOS 7.0'
  sims[:air_min] = 'iPad Retina (64-bit) - Simulator - iOS 7.0'

  sims[:ipad]     = 'iPad Retina - Simulator - iOS 7.1'
  sims[:ipad_mid] = 'iPad Retina - Simulator - iOS 7.0'
  sims[:ipad_min] = 'iPad Retina - Simulator - iOS 6.1'

  sims[:iphone4s]     = 'iPhone Retina (3.5-inch) - Simulator - iOS 7.1'
  sims[:iphone4s_mid] = 'iPhone Retina (3.5-inch) - Simulator - iOS 7.0'
  sims[:iphone4s_min] = 'iPhone Retina (3.5-inch) - Simulator - iOS 6.1'

  sims[:iphone5s]     = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
  sims[:iphone5s_mid] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.0'
  sims[:iphone5s_min] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.0'

  sims[:iphone5]     = 'iPhone Retina (4-inch) - Simulator - iOS 7.1'
  sims[:iphone5_mid] = 'iPhone Retina (4-inch) - Simulator - iOS 7.0'
  sims[:iphone5_min] = 'iPhone Retina (4-inch) - Simulator - iOS 6.1'

  sims[:iphone_latest] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
  sims[:iphone_largest] = 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'

  sims[:default]     = 'iPhone Retina (4-inch) - Simulator - iOS 7.1'
end

if ENV["USER"] == "jenkins" or ENV['TRAVIS']
  formatter = "progress"
  keep_sim_open_after = "0"
else
  formatter = "Slowhandcuke::Formatter"
  keep_sim_open_after = "1"
end

%>

verbose: CALABASH_FULL_CONSOLE_OUTPUT=1 DEBUG=1
common: -f <%= formatter %> NO_STOP=<%= keep_sim_open_after %> --expand --no-multiline --no-source

ipad_tags:   --tags ~@iphone --tags ~@iphone_only
iphone_tags: --tags ~@ipad   --tags ~@ipad_only

app:           APP=LPSimpleExample-cal.app

simulator:     -p common --tags ~@device_only --tags ~@device -p app
sim61_sl:      -p simulator LAUNCH_VIA=sim_launcher DEVICE_TARGET='iPhone (3.5-inch) - Simulator - iOS 6.1'

simulators:         SIMULATORS="<%= sims %>"
ipad2:              -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad2] %>"
ipad2_mid:          -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad2_mid] %>"
ipad2_min:          -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad2_min] %>"

air:                -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:air] %>"
air_mid:            -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:air_mid] %>"
air_min:            -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:air_min] %>"

ipad:               -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad] %>"
ipad_mid:           -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad_mid] %>"
ipad_min:           -p simulator -p ipad_tags DEVICE_TARGET="<%= sims[:ipad_min] %>"

iphone4s:           -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone4s] %>"
iphone4s_mid:       -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone4s_mid] %>"
iphone4s_min:       -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone4s_min] %>"

iphone5:            -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5] %>"
iphone5_mid:        -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5_mid] %>"
iphone5_min:        -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5_min] %>"

iphone5s:           -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5s] %>"
iphone5s_mid:       -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5s_mid] %>"
iphone5s_min:       -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:iphone5s_min] %>"

iphone_latest:      -p simulator DEVICE_TARGET="<%= sims[:iphone_latest] %>"
iphone_largest:     -p simulator DEVICE_TARGET="<%= sims[:iphone_largest] %>"

default:            -p simulator -p iphone_tags DEVICE_TARGET="<%= sims[:default] %>"

# required only for devices
bundle_id:    BUNDLE_ID=com.lesspainful.example.LPSimpleExample-cal

device_common:  -p bundle_id --tags ~@simulator --tags ~@simulator_only

hatp:  DEVICE_TARGET=<%= devices[:hatp][:udid] %> DEVICE_ENDPOINT=<%= devices[:hatp][:ip] %> -p device_common
neptune:  DEVICE_TARGET=<%= devices[:neptune][:udid] %> DEVICE_ENDPOINT=<%= devices[:neptune][:ip] %> -p device_common
venus:  DEVICE_TARGET=<%= devices[:venus][:udid] %> DEVICE_ENDPOINT=<%= devices[:venus][:ip] %> -p device_common
mars:  DEVICE_TARGET=<%= devices[:mars][:udid] %> DEVICE_ENDPOINT=<%= devices[:mars][:ip] %> -p device_common
uranus:  DEVICE_TARGET=<%= devices[:uranus][:udid] %> DEVICE_ENDPOINT=<%= devices[:uranus][:ip] %> -p device_common

